import tx_types as TX_TYPE

FEES = {
    TX_TYPE.COIN_SEND: 10,
    TX_TYPE.COIN_BUY: 100,
    TX_TYPE.COIN_CREATE: 100,
    TX_TYPE.COIN_SELL: 100,
    TX_TYPE.COIN_MULTISEND: 8,
    TX_TYPE.COIN_SELL_ALL: 100,
    TX_TYPE.COIN_REDEEM_CHECK: 30,
    TX_TYPE.VALIDATOR_CANDIDATE: 10000,
    TX_TYPE.VALIDATOR_DELEGATE: 200,
    TX_TYPE.VALIDATOR_SET_ONLINE: 100,
    TX_TYPE.VALIDATOR_SET_OFFLINE: 100,
    TX_TYPE.VALIDATOR_UNBOND: 200,
    TX_TYPE.VALIDATOR_CANDIDATE_EDIT: 10000,
    TX_TYPE.MULTISIG_CREATE_WALLET: 100,
    TX_TYPE.MULTISIG_CREATE_TX: 100,
    TX_TYPE.MULTISIG_SIGN_TX: 100,
    TX_TYPE.PROPOSAL_SUBMIT: 0,
    TX_TYPE.PROPOSAL_VOTE: 0,
    TX_TYPE.SWAP_HTLT: 33000,
    TX_TYPE.SWAP_REDEEM: 0,
    TX_TYPE.SWAP_REFUND: 0,
}


def get_message_fee(msg):
    pass